/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "accel.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//Glow LEDs in direction of inclination when axis value is above some fixed threshold value.
int main(void) {

	LIS_Data val;
	SystemInit();
	LedInit(LED_BLUE_PIN);
	LedInit(LED_GREEN_PIN);
	LedInit(LED_RED_PIN);
	LedInit(LED_ORANGE_PIN);
	LIS_Init(); //initialize accel
	while(1) {
		if(LIS_IsDataAvail()) // check if new data avail
		{
			val = LIS_GetData(); // get the new data
			if(val.x>=3000)
			LedOn(LED_BLUE_PIN);
			else if(val.x<=3000)
			LedOff(LED_BLUE_PIN);
			else if(val.y>=3000)
			LedOn(LED_GREEN_PIN);
			else if(val.y<=3000)
			LedOff(LED_GREEN_PIN);
			else if(val.z>=3000)
			LedOn(LED_ORANGE_PIN);
			else if(val.z<=3000)
			LedOff(LED_ORANGE_PIN);
			else
			LedOn(LED_RED_PIN);

		}
		DelayMs(1000);
	}
	return 0;
}
