/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define BB_BASE			0x40000000
#define BB_ALIAS_BASE 	0x42000000

//#define BIT_WORD_OFFSET(regr,bit) 	(((uint32_t)regr-BB_BASE)*32 + (bit)*4)
#define BIT_WORD_OFFSET(regr,bit) 	((((uint32_t)regr-BB_BASE)<<5) + ((bit)<<2))
#define BIT_WORD_ADDR(regr,bit) 	(BB_ALIAS_BASE + BIT_WORD_OFFSET(regr,bit))
#define BIT_WORD_VAL(regr,bit)		(*(uint32_t*)BIT_WORD_ADDR(regr,bit))

int main(void) {
	SystemInit();
	// enable GPIOD clock
	RCC->AHB1ENR |= BV(3);
	// GPIOD as output regr -- MODER
	BIT_WORD_VAL(&GPIOD->MODER, 25) = 0; //GPIOD->MODER &= ~BV(12*2 + 1);
	BIT_WORD_VAL(&GPIOD->MODER, 24) = 1; //GPIOD->MODER |= BV(12*2);
	// GPIOD as pushpull output
	BIT_WORD_VAL(&GPIOD->OTYPER, 12) = 0; //GPIOD->OTYPER &= ~BV(12);
	// GPIOD with no pullup pulldown resistors
	BIT_WORD_VAL(&GPIOD->PUPDR, 25) = 0; //GPIOD->PUPDR &= ~BV(12*2 + 1);
	BIT_WORD_VAL(&GPIOD->PUPDR, 24) = 0; //GPIOD->PUPDR &= ~BV(12*2);
	// GPIOD with low speed
	BIT_WORD_VAL(&GPIOD->OSPEEDR, 25) = 0; //GPIOD->OSPEEDR &= ~BV(12*2 + 1);
	BIT_WORD_VAL(&GPIOD->OSPEEDR, 24) = 0; //GPIOD->OSPEEDR &= ~BV(12*2);

	while(1) {
		//GPIOD->ODR bit 12 = 1;
		BIT_WORD_VAL(&GPIOD->ODR, 12) = 1;
		//Delay
		DelayMs(1000);
		//GPIOD->ODR bit 12 = 0;
		BIT_WORD_VAL(&GPIOD->ODR, 12) = 0;
		//Delay
		DelayMs(1000);
	}
	return 0;
}













