/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[32];
	SystemInit();
	UartInit(9600);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	int choice;
	UartPuts("Hello DESD!\r\n");
	UartPuts("God Bless You!\r\n");
	while(1) {
		UartGets(str);

		UartPuts("enter choice 1-4 :1. Red Led On 2. Red Led Off 3. Blue Led On 4. Blue Led Off");
		sscanf(str, "%d", &choice);
		switch(choice) {
		case 1:
			LedOn(LED_RED_PIN);
			break;
		case 2:
			LedOff(LED_RED_PIN);
			break;
		case 3:
			LedOn(LED_BLUE_PIN);
			break;
		case 4:
			LedOff(LED_BLUE_PIN);
			break;
		}



	}
	return 0;
}





