/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include<string.h>
#include "switch_intr.h"
#include "i2c_lcd.h"
//#include "i2c.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//count=1->lcd display name;  2->scroll name on lcd; 3->lcd off
int main(void) {
	SystemInit();
	SwitchInit();
	char str[32];

	int ret = Lcd_Init();
	if(ret){
	sprintf(str,"Hii");
	Lcd_Puts(LCD_LINE1, str);
	}
	while(1) {

		while(SwitchExtiFlag == 0)
			;
		if(ret){
		sprintf(str,"Welcome");
		Lcd_Puts(LCD_LINE1, str);
		}
		if(c==1){
			if(ret){

			sprintf(str,"Manish Vemula");
			Lcd_Puts(LCD_LINE1, str);
			}
			SwitchExtiFlag = 0;
		}
		else if(c==2){
			if(ret) {
						for(int i=0; i<=100 ;i++){
						sprintf(str,"Manish Vemula");
						DelayMs(500);
						Lcd_Puts(LCD_LINE1, str);
						}
						DelayMs(200);
						}
			SwitchExtiFlag = 0;
		}
		else if(c>2){
			display_off();
			SwitchExtiFlag = 0;
		}



	}
	return 0;
}
























