/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/***Use TIM7 to generate interrupt after
 every 1 second. Increment a global count in interrupt handler.
 Display count value on LCD (I2C based).*/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "timer.h"
#include "i2c_lcd.h"
#include "switch_intr.h"
#include<string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	SystemInit();
	Timer_Init(5000);
	SwitchInit();
	int ret=Lcd_Init();
	if(ret){
	char str[32];
while(1){
	Lcd_Puts(LCD_LINE1, str);
	sprintf(str,"count is %d",c);
}
	}
	return 0;
}




