/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "timer.h"
#include "led.h"
#include "adc.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
/**Optional assignment:
Read ADC input periodially (after 100 ms). Change blinking rate of LEDs based on ADC reading**/

int main(void) {
	SystemInit();
	Timer_Init();
	uint16_t val;
	char str[32];
	ADC_Init();
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	while(1){
			val = ADC_GetValue();
			sprintf(str, "ADC = %u\r\n", val);
			if(val>10){
			LedBlink(LED_RED_PIN,100);
			}
			else{
				LedBlink(LED_BLUE_PIN,100);
			}
		}

	return 0;
}
